apiVersion: v1
kind: Service
metadata:
  name: microbot
  namespace: default
  labels:
    k8s-app: microbot
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "microbot"
spec:
  selector:
    k8s-app: microbot
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - $EXT_IP1
    

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: microbot
  namespace: default
  labels:
    k8s-app: microbot
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 25
  selector:
    k8s-app: microbot
    version: v1
  template:
    metadata:
      labels:
        k8s-app: microbot
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: microbot
        image: dontrebootme/microbot:v1
        resources:
          limits:
            cpu: 25m
            memory: 32Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5

